/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 */
/**
 * MIT License
 *
 * Copyright (C) 2024 Huawei Device Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
 
#ifndef TESTER_HARMONY_KEYBOARD_CONTROLLER_SRC_MAIN_CPP_KEYBOARDCONTROLLERVIEWCOMPONENTDESCRIPTOR_H
#define TESTER_HARMONY_KEYBOARD_CONTROLLER_SRC_MAIN_CPP_KEYBOARDCONTROLLERVIEWCOMPONENTDESCRIPTOR_H

#ifndef KEYBOARDCONTROLLERVIEWCOMPONENTDESCRIPTOR_H
#define KEYBOARDCONTROLLERVIEWCOMPONENTDESCRIPTOR_H

/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 */

/**
 * This code was generated by "react-native codegen-harmony"
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 *
 * @generatorVersion: 1
 */
#pragma once

#include <react/renderer/core/ConcreteComponentDescriptor.h>
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <react/renderer/components/view/ViewShadowNode.h>
#include <react/renderer/core/propsConversions.h>
#include "EventEmitters.h"

namespace facebook {
namespace react {

inline const char KeyboardControllerViewName[] = "RNKeyboardControllerView";

class KeyboardControllerViewProps : public ViewProps {
public:
    bool enabled = false;
    bool statusBarTranslucent = false;
    bool navigationBarTranslucent = false;
    bool preserveEdgeToEdge = false;
    bool disableSystemKeyboardAvoidance = false;
    KeyboardControllerViewProps() = default;

    KeyboardControllerViewProps(const PropsParserContext &context, const KeyboardControllerViewProps &sourceProps,
                                const RawProps &rawProps)
        : ViewProps(context, sourceProps, rawProps),
          enabled(convertRawProp(context, rawProps, "enabled", sourceProps.enabled, {false})),
          statusBarTranslucent(convertRawProp(context, rawProps, "statusBarTranslucent",
                                                    sourceProps.statusBarTranslucent, {false})),
          navigationBarTranslucent(convertRawProp(context, rawProps, "navigationBarTranslucent",
                                                        sourceProps.navigationBarTranslucent, {false})),
          preserveEdgeToEdge(convertRawProp(context, rawProps, "preserveEdgeToEdge", sourceProps.preserveEdgeToEdge, {false})),
          disableSystemKeyboardAvoidance(convertRawProp(context, rawProps, "disableSystemKeyboardAvoidance",
                                                        sourceProps.disableSystemKeyboardAvoidance, {false})){}
};

using KeyboardControllerViewShadowNode =
    ConcreteViewShadowNode<KeyboardControllerViewName, KeyboardControllerViewProps, KeyboardControllerViewEventEmitter>;

class KeyboardControllerViewComponentDescriptor final
    : public ConcreteComponentDescriptor<KeyboardControllerViewShadowNode> {
public:
    KeyboardControllerViewComponentDescriptor(ComponentDescriptorParameters const &parameters)
        : ConcreteComponentDescriptor(parameters) {}
};


} // namespace react
} // namespace facebook

#endif

#endif
